### PR TITLE
Write an introduction to JOBS.

### PR DESCRIPTION
**Pull request by jlouis**
See title. No brainer.

### CODE REVIEW

**Comment by uwiger** [comment]
Great, but what I would prefer is to have the intro in doc/overview.edoc, and have edown configured to generate the README.md

**Comment by jlouis** [comment]
I'll be moving it to that part then and generate appropriate links from the README.md file then.

**Comment by jlouis** [comment]
Ulf, this new push uses edown to generate the README.md from overview.doc. The links doesn't work but will as soon as we push it to esl/jobs. I hope this is closer to what you had in mind when considering to use edown for README.md generation :)

**Comment by uwiger** [comment]
There - merged, pulled, regenerated and re-pushed. Just doing an automatic merge on github wasn't enough. :)

**Pull request merged**
